### ISSUE TITLE
提取某游戏key无效

### ISSUE THREAD

**Issue by NatsusakiYomi** [Dir-A/ExHIBIT_KeyFinder#1]
对Skyfish的游戏はるかぜどりに、とまりぎを按照说明使用了大佬的提取工具但生成不了相应的key文件（出现游戏窗口一段时间后自动退出）。
如果大佬需要游戏本体可以直接发过去。

**Comment by Dir-A** [comment]
因为这个游戏本身就是明文，旧版本似乎都没加密。
![QQ截图20230520190041](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/79064817/f95ab31f-eb2a-4444-af91-26ac5e849b6c)

**Comment by NatsusakiYomi** [comment]
感谢，之前没有检查游戏是否加密
