### ISSUE TITLE
Request for redirecting to Shift-jis

### ISSUE THREAD

**Issue by Cosetto** [Dir-A/ExHIBIT_KeyFinder#2]
Bro, can you do it again like Eden? The problem is like Eden, it can't display shift-jis characters in message box, but the backlog can display normally.
This is the game [link](https://vndb.org/r107577), you can grab it on F95.
Also if you need, this for dumping/inserting rld [link](https://github.com/regomne/chinesize/tree/master/ExHIBIT/extRld)

**Comment by Dir-A** [comment]
[Uchikoi_JP.zip](https://github.com/Dir-A/ExHIBIT_KeyFinder/files/11785992/Uchikoi_JP.zip)

Try this

``` C
#include <Windows.h>
#include "../../ThirdParty/detours/include/detours.h"

#pragma comment(lib,"../../ThirdParty/detours/lib.X86/detours.lib")

typedef HFONT(WINAPI* pCreateFontA)(INT cHeight, INT cWidth, INT cEscapement, INT cOrientation, INT cWeight, DWORD bItalic, DWORD bUnderline, DWORD bStrikeOut, DWORD iCharSet, DWORD iOutPrecision, DWORD iClipPrecision, DWORD iQuality, DWORD iPitchAndFamily, LPCSTR pszFaceName);
static pCreateFontA sg_fnCreateFontA_Raw = CreateFontA;

typedef HFONT(WINAPI* pCreateFontIndirectA)(CONST LOGFONTA* lplf);
static pCreateFontIndirectA sg_fnCreateFontIndirectA_Raw = CreateFontIndirectA;

typedef HMODULE(WINAPI* pLoadLibraryExA)(LPCSTR lpLibFileName, HANDLE hFile, DWORD dwFlags);
static pLoadLibraryExA sg_fnLoadLibraryExA_Raw = LoadLibraryExA;

BOOL DetourAttachFunc(PVOID ppRawFunc, PVOID pNewFunc)
{
	DetourRestoreAfterWith();
	DetourTransactionBegin();
	DetourUpdateThread(GetCurrentThread());

	LONG erroAttach = DetourAttach((PVOID*)ppRawFunc, pNewFunc);
	LONG erroCommit = DetourTransactionCommit();

	if (erroAttach == NO_ERROR && erroCommit == NO_ERROR) return false;

	MessageBoxW(NULL, L"DetourAttach Failed!!", NULL, NULL);

	return true;
}

BOOL DetourDetachFunc(PVOID ppRawFunc, PVOID pNewFunc)
{
	DetourRestoreAfterWith();
	DetourTransactionBegin();
	DetourUpdateThread(GetCurrentThread());

	LONG erroDetach = DetourDetach((PVOID*)ppRawFunc, pNewFunc);
	LONG erroCommit = DetourTransactionCommit();

	if (erroDetach == NO_ERROR && erroCommit == NO_ERROR) return false;

	MessageBoxW(NULL, L"DetourDetachFunc Failed!!", NULL, NULL);

	return true;
}

BOOL WriteMemory(LPVOID lpAddress, LPCVOID lpBuffer, SIZE_T nSize)
{
	DWORD old = 0;
	BOOL protect = VirtualProtectEx(GetCurrentProcess(), lpAddress, nSize, PAGE_EXECUTE_READWRITE, &old);
	BOOL written = WriteProcessMemory(GetCurrentProcess(), lpAddress, lpBuffer, nSize, NULL);

	if (protect && written) return TRUE;

	MessageBoxW(NULL, L"WriteMemory Failed!!", NULL, NULL);

	return FALSE;
}


HMODULE WINAPI LoadLibraryExA_New(LPCSTR lpLibFileName, HANDLE hFile, DWORD dwFlags)
{
	HMODULE module_dll = sg_fnLoadLibraryExA_Raw(lpLibFileName, hFile, dwFlags);

	if (!strcmp(lpLibFileName, "resident.dll"))
	{
		static BYTE path_0[] = { 0x90, 0x90, 0x90, 0x90, 0x90, 0x90, 0x90 };
		static BYTE path_1[] = { 0x90, 0x90, 0x3C, 0x81, 0x72, 0x0E };
		static BYTE path_2[] = { 0x90, 0x90, 0x90, 0x40, 0x82, 0xF9, 0x81, 0x72, 0x11 };
		WriteMemory((LPVOID)((DWORD)module_dll + 0x1E7BE3), path_0, sizeof(path_0));
		WriteMemory((LPVOID)((DWORD)module_dll + 0x1E934F), path_0, sizeof(path_0));
		WriteMemory((LPVOID)((DWORD)module_dll + 0x1E7BF6), path_1, sizeof(path_1));
		WriteMemory((LPVOID)((DWORD)module_dll + 0x1E935F), path_2, sizeof(path_2));

		DetourDetachFunc(&sg_fnLoadLibraryExA_Raw, LoadLibraryExA_New);
	}

	return module_dll;
}

HFONT WINAPI CreateFontA_New(INT cHeight, INT cWidth, INT cEscapement, INT cOrientation, INT cWeight, DWORD bItalic, DWORD bUnderline, DWORD bStrikeOut, DWORD iCharSet, DWORD iOutPrecision, DWORD iClipPrecision, DWORD iQuality, DWORD iPitchAndFamily, LPCSTR pszFaceName)
{
	return sg_fnCreateFontA_Raw(cHeight, cWidth, cEscapement, cOrientation, cWeight, bItalic, bUnderline, bStrikeOut, 0x80, iOutPrecision, iClipPrecision, iQuality, iPitchAndFamily, "MS Gothic");
}

HFONT WINAPI CreateFontIndirectA_New(LOGFONTA* lplf)
{
	lplf->lfCharSet = 0x80;
	strcpy_s(lplf->lfFaceName, 32, "MS Gothic");
	return sg_fnCreateFontIndirectA_Raw(lplf);
}

VOID StartHook()
{
	DetourAttachFunc(&sg_fnLoadLibraryExA_Raw, LoadLibraryExA_New);
	DetourAttachFunc(&sg_fnCreateFontA_Raw, CreateFontA_New);
	DetourAttachFunc(&sg_fnCreateFontIndirectA_Raw, CreateFontIndirectA_New);
}

BOOL APIENTRY DllMain(HMODULE hModule, DWORD  ul_reason_for_call, LPVOID lpReserved)
{
	switch (ul_reason_for_call)
	{
	case DLL_PROCESS_ATTACH:
		StartHook();
		break;
	case DLL_THREAD_ATTACH:
		break;
	case DLL_THREAD_DETACH:
		break;
	case DLL_PROCESS_DETACH:
		break;
	}
	return TRUE;
}

VOID  __declspec(dllexport) DirA() {}
```

**Comment by Cosetto** [comment]
Thanks so much bro, you did it again. And do you have tutorial how to find the addresses by any chance? There're some other games that I want to test on. I have IDA and xdb32 on my pc

**Comment by Dir-A** [comment]
Maybe next week. I'm busy now.
You can give one of the game name and we can pick one to demo next week
[ExHIBIT_MOD.zip](https://github.com/Dir-A/ExHIBIT_KeyFinder/files/11796455/ExHIBIT_MOD.zip)

**Comment by Cosetto** [comment]
Thanks bro, you can try with two previous Uchikano, Imouto Paradise 3, Sakura Mori Dreamers

**Comment by Cosetto** [comment]
Bro, I also wonder how to use your subtitle tool, especially will it work for game has protection like Alpharom? At first, I really thought it was a dll.

**Comment by Dir-A** [comment]
It is possible to put it in to dll.
That project is still under development and many parts are not perfect yet.
I recently had my final exams for the semester,
So I haven't had time to perfect it yet.

**Comment by Cosetto** [comment]
So, when we're done with this, can you check on Aonatsu Line with the subtitle tool? At the start of the game, there's a monologue scene with no textbox, so we can have it as an example.
Here's the address to hijack Alpharom of the game:
```
	if (dwSize == 0x00596000)
	{
		if (*(DWORD*)0x00B154D0 == 0x5004EC83)
		{
			*(DWORD*)0x00B154D0 = 0x90000CC2;
			DetourTransactionBegin();
			DetourDetach(&(PVOID&)rawVirtualAlloc, newVirtualAlloc);
			DetourTransactionCommit();
		}
	}

```

**Comment by Cosetto** [comment]
Is there any update about Exhibit yet?

**Comment by Dir-A** [comment]
https://anonfiles.com/j0TaM200zb/2023_07_07_22_55_51_mkv

VNSubtitle_GDI is still under development and is not available yet

**Comment by Cosetto** [comment]
Thanks again bro, I'm looking forward to seeing the subtitle tool.

**Comment by Cosetto** [comment]
Bro, can you check Moonstone's exhibit. I couldn't find the "push ebp" instruction to toggle breakpoint. I think it's an old version of the engine, the game I am testing with is Imouto paradise 3, you can grab it from hsuki
![image](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/81801486/1de7e1f3-5bda-4410-acff-7db16c609e3d)
![image](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/81801486/ec30b31d-632b-4667-8266-931a4753520f)

**Comment by Dir-A** [comment]
``` c
VOID PatchAsm(DWORD hDll)
{
	static BYTE path_10[] = 
	{ 
		0x90,  // nop
		0x90,  // nop
		0x90,  // nop
		0x90,  // nop
		0x90,  // nop
		0x90,  // nop
		0x90   // nop
	};
	WriteMemory((LPVOID)(hDll + 0x1B8574), path_10, sizeof(path_10));

	static BYTE path_11[] = 
	{ 
		0x90,             // nop
		0x90,             // nop
		0x90,             // nop
		0x82, 0xFA, 0x81, // cmp dl, 0x81
		0x72, 0x0D        // jb
	};
	WriteMemory((LPVOID)(hDll + 0x1B858D), path_11, sizeof(path_11));


	static BYTE path_20[] =
	{
		0x90, // nop
		0x90, // nop
		0x90, // nop
		0x90, // nop
		0x90  // nop
	};
	WriteMemory((LPVOID)(hDll + 0x1B861D), path_20, sizeof(path_20));

	static BYTE path_21[] = 
	{ 
		0x90, // nop
		0x90  // nop
	};
	WriteMemory((LPVOID)(hDll + 0x1B8626), path_21, sizeof(path_21));


	static BYTE path_22[] = 
	{ 
		0x90,             // nop
		0x90,             // nop
		0x90,             // nop
		0x83, 0xC0, 0x01, // add eax, 0x1
		0x82, 0xF9, 0x81, // cmp cl, 0x81
		0x72, 0x10        // jb
	};
	WriteMemory((LPVOID)(hDll + 0x1B862E), path_22, sizeof(path_22));
}
```
![QQ截图20230708150532](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/79064817/9931cf63-2b6f-40a7-b151-4141bb85edf3)

![QQ截图20230708150558](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/79064817/79672f4e-edb8-428b-949c-aa88f94b5fd6)

**Comment by Cosetto** [comment]
Thanks bro!

**Comment by Cosetto** [comment]
Oh yeah bro, about the subtitle, I found that [vntextproxy](https://github.com/arcusmaximus/VNTranslationTools/blob/main/VNTextProxy/Subtitles/SubtitleLine.cpp) of vntranslationtools also has the subtitle. Unfortunately, the owner didn't leave any instruction to use :((

**Comment by Dir-A** [comment]
It looks like it's rendering the font to the BITMAP in memory via GDI+
Based on the way it is implemented, 
you should need to find the memory for the BITMAP that is drawn on the screen in real time when you use it。
And where the video starts and ends playback

I recently rewrote my subtitle project rendering module using Direct2D
and my project was realized by attaching a transparent window to the game's window
So it's just a matter of finding where the video starts playing and where it ends.

**Comment by Cosetto** [comment]
Looking forward to it!

**Comment by Cosetto** [comment]
Bro, there's something I still don't get it. How do I make the subtitle tool work, like do I drop game.exe to it?

**Comment by Dir-A** [comment]
It doesn't work yet, only the text rendering part is done

**Comment by Cosetto** [comment]
Bro, can you have a look at [this one](https://vndb.org/r106718)
[Link](https://pixeldrain.com/u/SwdR2r7j), pw: ryuugames.com
![image](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/81801486/d994c938-ca88-4bcd-a346-f661ea6179c7)
It seems like Uchikano method doesn't work with this game

**Comment by Cosetto** [comment]
> Bro, can you have a look at [this one](https://vndb.org/r106718) [Link](https://pixeldrain.com/u/SwdR2r7j), pw: ryuugames.com ![image](https://private-user-images.githubusercontent.com/81801486/287291802-d994c938-ca88-4bcd-a346-f661ea6179c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjQ5NzQsIm5iZiI6MTcwMzIyNDY3NCwicGF0aCI6Ii84MTgwMTQ4Ni8yODcyOTE4MDItZDk5NGM5MzgtY2E4OC00YmNkLWEzNDYtZjY2MWVhNjE3OWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA1NTc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMDkzMDNjMmJhMzQ4ZTJkOTRjOGJkYjBkY2YwODczNmUxZTc1NGFjY2ZhMTZlNGNhZjRkNjZmNmViYzg2ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VJeGR9bvhQmDK7zIfKJ4Y9e4GFCE_hm1xYLd2BFXSvU) It seems like Uchikano method doesn't work with this game

@Dir-A Bro, can you check this one

**Comment by Dir-A** [comment]
Next month, no time for now.

**Comment by Cosetto** [comment]
> Bro, can you have a look at [this one](https://vndb.org/r106718) [Link](https://pixeldrain.com/u/SwdR2r7j), pw: ryuugames.com ![image](https://private-user-images.githubusercontent.com/81801486/287291802-d994c938-ca88-4bcd-a346-f661ea6179c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjYzODQsIm5iZiI6MTcwNTIyNjA4NCwicGF0aCI6Ii84MTgwMTQ4Ni8yODcyOTE4MDItZDk5NGM5MzgtY2E4OC00YmNkLWEzNDYtZjY2MWVhNjE3OWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA5NTQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZjI5MzkyMmVkNzU5OWU1YTcyZmRiZGMwYjMzZDBkMTcwMGU4YWViMjI5NDk1YmNmYmM3YWQxNDZmMTEyY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-9b14Q_grOd-Qfr1xinwYdhytkpSjfNDzVNaOrJ6WDE) It seems like Uchikano method doesn't work with this game

Bro can you check on this?

**Comment by Cosetto** [comment]
> Bro, can you have a look at [this one](https://vndb.org/r106718) [Link](https://pixeldrain.com/u/SwdR2r7j), pw: ryuugames.com ![image](https://private-user-images.githubusercontent.com/81801486/287291802-d994c938-ca88-4bcd-a346-f661ea6179c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2OTE3NDIsIm5iZiI6MTcwNjY5MTQ0MiwicGF0aCI6Ii84MTgwMTQ4Ni8yODcyOTE4MDItZDk5NGM5MzgtY2E4OC00YmNkLWEzNDYtZjY2MWVhNjE3OWM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDA4NTcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmODZmYWJhOGQ2NjA2MTEyZjFjZGMwZDcxOGU1NDViYWI5ZjM3Y2IxMTM3Yzg2NTg5Y2E4NDI5MjQ1NmRjNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.icvnqcMpr5s1cs3tfiKUWeyVE1eBxDbvvaGo-LqJhBQ) It seems like Uchikano method doesn't work with this game

Bro, can you check this game?

**Comment by Dir-A** [comment]
![QQ截图20240201201532](https://github.com/Dir-A/ExHIBIT_KeyFinder/assets/79064817/807170d5-eb06-4af2-800e-278965a07461)
[ExHIBIT_MOD.zip](https://github.com/Dir-A/ExHIBIT_KeyFinder/files/14125183/ExHIBIT_MOD.zip)
just try

**Comment by Cosetto** [comment]
Thanks bro
